Pilot updates to exercise and instructor notes
carpentries/lesson-development-training pull request #139
Opened 2022-08-26 14:24 UTC by sstevens2

Updates from issue #95 .  This only includes the first episode I taught. I will put in separate PRs for the other episodes I taught and changed.

I also updated these in the template CodiMD and will also update that before this gets merged with any additional changes.

2022-08-26 14:33 UTC, sstevens2 commented
@tobyhodges general question about these notes.  I added a few bulleted lists as notes in the CodiMD that summarize some of the info in the paragraphs.  Do you think we should include those notes in the lesson somewhere or are they okay living separately in the CodiMD template?  In this PR I put them in the instructor notes but there are more in the next episode.

2022-08-29 09:07 UTC, tobyhodges commented
It's an interesting question, @sstevens2. I guess it is relatively straightforward to generate a lot of the template CodiMD from the fenced divs for objectives, questions, key points, and exercises. 

Perhaps @zkamvar might consider adding some functionality to `sandpaper` that would allow us to mark up other sections of episode content to be extracted for inclusion in a CodiMD notes template?

2022-08-29 09:20 UTC, tobyhodges requested changes
One typo fix, and a couple of suggestions to make the examples in the exercise more meaningful as guidance for trainees.

2022-08-29 09:20 UTC, tobyhodges commented on episodes/15-narrative.md
> +- Complexity - Is it easy to understand? Is it sufficiuently authentic?
```suggestion
- Complexity - Is it easy to understand? Is it sufficiently authentic?
```

2022-08-29 09:20 UTC, tobyhodges commented on episodes/15-narrative.md
> +Exercise to find the correct widget (a slider widget) for an action and modify the script to use it -> In the lesson the instructor introduces the cheatsheet and documentation and then creates a drop
```suggestion
Exercise to find the correct widget (a slider) for an action and modify the script to use it -> 
In the lesson the instructor introduces a cheatsheet and documentation for interactive widgets and 
then creates a dropdown widget for the application. 
The slider widget required in the exercise has not been demonstrated but
the preceding example shows all of the necessary steps to add a widget, 
and provides the supporting information that learners can consult to discover
how to implement the specific tool.
```

2022-08-29 09:20 UTC, tobyhodges commented on episodes/15-narrative.md
> +Exercise to load and inspect americas csv -> In the lesson, load the oceania data table and explore the values with a few different functions.
```suggestion
Exercise to load and inspect CSV file for Americas -> 
In the lesson, the Instructor demonstrates how to load the data table for another continent (Oceania)
and explores the values with a few different functions.
This shows learners how to call the function to load the CSV into a data frame,
and demonstrates what success looks like for this task.
```

2022-08-29 16:23 UTC, zkamvar commented
> It's an interesting question, @sstevens2. I guess it is relatively straightforward to generate a lot of the template CodiMD from the fenced divs for objectives, questions, key points, and exercises.
> 
> Perhaps @zkamvar might consider adding some functionality to `sandpaper` that would allow us to mark up other sections of episode content to be extracted for inclusion in a CodiMD notes template?

Make a PR for it and it will be on my radar. The initial wireframes actually do have room for buttons to export a lesson outline, so that could be something that we could wrap into this feature you want.

2022-09-02 12:39 UTC, tobyhodges approved these changes

2022-09-02 12:39 UTC, merged