Adding instructor note about piloting to learn
carpentries/lesson-development-training pull request #141
Opened 2022-08-26 15:09 UTC by sstevens2

Drafted a bit of text in the instructor notes on the reoccurring theme of piloting as a learning opportunity.
It is a very quick draft based on the issue so feedback highly welcome.  I was especially undecided if I should write it as a direct recommendation to the reader using "you" or not.

Closes #96

2022-08-29 09:28 UTC, tobyhodges requested changes
I like this note, and I think some "you could"/"you might" is good. But I have reworded to remove the "you should" because I expect other Trainers will want to frame things differently and I don't want to discourage that.

2022-08-29 09:28 UTC, tobyhodges commented on instructors/instructor-notes.md
> +when talking about the ways in which piloting a lesson can help you improve it.
```suggestion
We have found it helpful to frame the discussion this way and to draw on our own experience 
when talking about the ways in which piloting a lesson can help to improve it.
```

2022-08-29 09:28 UTC, tobyhodges commented on instructors/instructor-notes.md
> +when you piloted a workshop and realize there was a concept missing in the demo/narrative that the learners needed in order to be able to complete the exercise.
```suggestion
when you piloted a workshop and realized there was a concept missing in the demo/narrative
that learners needed in order to be able to complete the exercise.
```

2022-09-13 15:33 UTC, sstevens2 commented on instructors/instructor-notes.md
> +when talking about the ways in which piloting a lesson can help you improve it.
Good idea!

2022-09-15 10:30 UTC, tobyhodges approved these changes

2022-09-15 10:30 UTC, tobyhodges commented
Thanks @sstevens2 👍

2022-09-15 10:30 UTC, merged