initialise Trainer Notes page
carpentries/lesson-development-training pull request #155
Opened 2022-11-10 09:42 UTC by tobyhodges

Started building up the page of trainer notes

2022-11-23 19:28 UTC, sstevens2 commented on instructors/instructor-notes.md
> +across each half-day.
I couldn't find the schedule mentioned below.  Do we still need to add a table or something with the schedule?

That said, do we want to maintain this manually if we rearrange the episodes for each day?

2022-11-23 19:29 UTC, sstevens2 requested changes
Not quite sure where the schedule mention is.  Should it be a table that shows which episodes are on each half day? Small concern about remembering to update the table if we rearrange anything.

2022-11-28 12:39 UTC, tobyhodges commented
Good catch @sstevens2. You are right that it is too early to provide a schedule now, and I have removed the sentence in 1fac2be

I think it may be helpful to include such a schedule at some point when the order and distribution of episodes has settled down a bit more. For example, it would enable us to remove the break .md files in the lesson site, instead pointing Trainers to this page (or somewhere else) for guidance on how to split the content over multiple days.

2022-11-28 23:14 UTC, sstevens2 approved these changes
That makes sense @tobyhodges.  I'll get this merged.

2022-11-28 23:14 UTC, merged