Add more example datasets and narratives
carpentries/lesson-development-training pull request #386
Opened 2024-08-01 15:51 UTC by anenadic

Fixes #316.

2024-09-05 15:57 UTC, tobyhodges commented on episodes/narrative.md
> +  teach how to use The Carpentries Workbench lesson template as we will see later on.
```suggestion
```

I would leave this one off the list, as 1. I may delete that repo soon, and 2. I don't think the recipe example os a particularly good fit as an example for a lesson -- the idea of a 'narrative' doesn't really hold. I will try to think of an alternative.

2024-09-05 16:01 UTC, tobyhodges commented
Thanks @anenadic, I am going to open another PR to add to this one before we merge.

2024-09-05 16:26 UTC, tobyhodges requested changes
Ok, I have made one more suggested change. If you are happy with these @anenadic, I think it is ready to go.

2024-09-06 12:51 UTC, anenadic commented
> Ok, I have made one more suggested change. If you are happy with these @anenadic, I think it is ready to go.

Happy with all the changes - hope the build runs successfully so we can merge this PR. 👍

2024-09-09 09:18 UTC, tobyhodges approved these changes

2024-09-09 09:18 UTC, merged