exercise deduplication
carpentries/lesson-development-training pull request #57
Opened 2022-06-06 19:36 UTC by sstevens2

Less to deduplicate than anticipated.  Let me know if you have any other feedback on this PR.

2022-06-07 10:54 UTC, tobyhodges requested changes
Minor typo fixes. Thank you @sstevens2 this is helpful. Do the episode timings add up correctly here, since the exercise was removed?

2022-06-07 10:54 UTC, tobyhodges commented on episodes/18-preparing.md
> +After reading [the information provided about the trial run task](../learners/trial_runs.md) and thinking about this task,
```suggestion
After reading [the information provided about the trial run task](../learners/trial-runs.md) and thinking about this task, 
```

2022-06-07 10:54 UTC, tobyhodges commented on episodes/19-wrap-up2.md
> +Please provide another round of feedback and spend sometime reflecting.
```suggestion
Please provide another round of feedback and spend some time reflecting.
```

2022-06-10 08:36 UTC, anenadic approved these changes
Happy for this to be merged.

2022-06-10 09:01 UTC, tobyhodges approved these changes

2022-06-10 09:02 UTC, merged